version: "3.8"

services:
  backendrest:
    build:
      context: .
      dockerfile: Dockerfile
    image: kazuh/backendrest:1.0
    container_name: backendrest
    restart: always
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=$MONGO_HOSTNAME
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
      - PORT_WEB=$PORT_WEB
      - environment=$environment
    ports:
      - "$PORT_WEB:$PORT_WEB"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    # command: ./wait.sh $MONGO_HOSTNAME:$MONGO_PORT -- /home/node/app/node_modules/.bin/nodemon app.js
  
  # db:
  #   image: mongo:4.1.8-xenial
  #   container_name: db
  #   restart: unless-stopped
  #   env_file: .env
  #   ports:
  #     - "$MONGO_PORT:$MONGO_PORT"
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
  #     - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
  #     - MONGO_INITDB_DATABASE=$MONGO_DB
  #   volumes:
  #     - dbdata:/data/db
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
